# Generated by Django 5.2 on 2025-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('admin', 'Admin')], max_length=100),
        ),
    ]
