# Generated by Django 5.2 on 2025-09-05 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='app.user'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='number_of_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='students',
            field=models.ManyToManyField(related_name='attendance', to='app.student'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='app.subject'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
