# Generated by Django 5.2 on 2025-09-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_attendancerecord_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='time',
            field=models.TimeField(),
        ),
    ]
